In [ ]:
# Librerie Generiche

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from time import time
import seaborn as sn

# Keras
import keras
from keras.utils import to_categorical

# Sklearn
import sklearn
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV,  RepeatedStratifiedKFold
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, accuracy_score, roc_curve, classification_report
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.utils.estimator_checks import check_estimator

np.random.seed(1234)
tf.random.set_seed(1234)

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
Music = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/PROGETTO MUSICA DSIM/DATASET/Music_datatset.csv')

In [ ]:
Music= Music.drop(columns=['Unnamed: 0'])
Music.head()

filename  Mean_ZCR   Var_ZCR  ...  Var_MFCC_19  Var_MFCC_20  Genre
0  blues.00000.wav  0.083045  0.000767  ...    55.062926    46.936036  Blues
1  blues.00001.wav  0.056040  0.001448  ...    51.106198    45.786282  Blues
2  blues.00002.wav  0.076291  0.001007  ...    46.639666    30.573022  Blues
3  blues.00003.wav  0.033309  0.000423  ...    37.259741    31.949340  Blues
4  blues.00004.wav  0.101461  0.001954  ...    62.910815    55.195162  Blues

[5 rows x 59 columns]

In [ ]:
data_X = Music.drop(columns=['filename', 'Genre'])
X = data_X.values
min_max_scaler_x = sklearn.preprocessing.MinMaxScaler()
X_scale = min_max_scaler_x.fit_transform(X)
X_scale

array([[0.242545  , 0.02520928, 0.63277922, ..., 0.08244974, 0.10950252,
        0.07825494],
       [0.1357779 , 0.04894396, 0.63727538, ..., 0.10299716, 0.09908115,
        0.0759467 ],
       [0.21584389, 0.03357507, 0.63393203, ..., 0.11641998, 0.08731703,
        0.04540464],
       ...,
       [0.39585688, 0.0576381 , 0.63386896, ..., 0.06482372, 0.07641965,
        0.04398425],
       [0.10685518, 0.0266249 , 0.63390025, ..., 0.05956411, 0.08886446,
        0.06693823],
       [0.21589764, 0.0741852 , 0.63389202, ..., 0.19239899, 0.15461065,
        0.08372859]])

In [ ]:
data_Y = Music['Genre']
Y = data_Y.values
LE = sklearn.preprocessing.LabelEncoder()
Y_label = LE.fit_transform(Y)

In [ ]:
X_scale.shape

(999, 57)

In [ ]:
Y_label.shape

(999,)

In [ ]:
X_train, X_test , y_train, y_test = train_test_split(X_scale, Y_label, test_size=0.2)

In [ ]:
X_train.shape

(799, 57)

In [ ]:
X_test.shape

(200, 57)

In [ ]:
y_train.shape

(799,)

In [ ]:
y_test.shape

(200,)

In [ ]:
y_train[100]

2

In [ ]:
# SVM

# Random Search

# Parameters to be tested in cross-validation
param_grid = {'C': [1e2, 5e2, 1e3],
          'gamma': [0.005, 0.01, 0.1, 0.5, 1.0], }

# Support Vector Machine initialization
clf_SVC = GridSearchCV(SVC(kernel='rbf', class_weight='balanced'), param_grid, cv=2)

# Training
t0 = time()
clf_SVC = clf_SVC.fit(X_train, y_train)
print('Training completed in %0.3fs' % (time() - t0))
# Test
y_pred_SVC = clf_SVC.predict(X_test)

# Classificaiton report
print('Classification report:')
print(classification_report(y_test, y_pred_SVC))

# Confusion matrix
print('Confusion matrix:')
cm = confusion_matrix(y_test, y_pred_SVC)
print(cm)

Training completed in 1.090s
Classification report:
              precision    recall  f1-score   support

           0       0.74      0.94      0.83        18
           1       0.81      0.91      0.86        23
           2       0.90      0.75      0.82        24
           3       0.76      0.64      0.70        25
           4       0.88      0.62      0.73        24
           5       0.85      0.73      0.79        15
           6       0.86      0.86      0.86        21
           7       0.60      0.80      0.69        15
           8       0.65      0.65      0.65        17
           9       0.64      0.78      0.70        18

    accuracy                           0.77       200
   macro avg       0.77      0.77      0.76       200
weighted avg       0.78      0.77      0.76       200

Confusion matrix:
[[17  0  1  0  0  0  0  0  0  0]
 [ 0 21  1  0  0  1  0  0  0  0]
 [ 0  0 18  1  0  1  0  2  0  2]
 [ 1  1  0 16  0  0  0  3  1  3]
 [ 2  0  0  1 15  0  2  2  2  0]
 [ 0  

In [ ]:
# Result of the cross validation for parameters selection SVM
print('Best parameters combination:')
print(' C: '+str(clf_SVC.best_estimator_.C))
print(' gamma: '+str(clf_SVC.best_estimator_.gamma))

Best parameters combination:
 C: 100.0
 gamma: 1.0


In [ ]:
# LOGISTIC REGRESSION

# Random Search

space = dict()
space['solver'] = ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']
space['penalty'] = ['none', 'l1', 'l2', 'elasticnet']
space['C'] = (range(1,1000))
space['multi_class'] = ['auto', 'ovr', 'multinomial']
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
model = LogisticRegression()

clf_LR = RandomizedSearchCV(model, space, scoring='accuracy', n_jobs=-1)
# Training
clf_LR = clf_LR.fit(X_train, y_train)

# Pred
y_pred_LR = clf_LR.predict(X_test)

# Classificaiton report
print('Classification report:')
print(classification_report(y_test, y_pred_LR))

# Confusion matrix
print('Confusion matrix:')
cm_LR = confusion_matrix(y_test, y_pred_LR)
print(cm_LR)

Classification report:
              precision    recall  f1-score   support

           0       0.94      0.83      0.88        18
           1       0.83      0.83      0.83        23
           2       0.72      0.54      0.62        24
           3       0.55      0.44      0.49        25
           4       0.90      0.79      0.84        24
           5       0.73      0.73      0.73        15
           6       0.81      0.81      0.81        21
           7       0.72      0.87      0.79        15
           8       0.67      0.71      0.69        17
           9       0.40      0.67      0.50        18

    accuracy                           0.71       200
   macro avg       0.73      0.72      0.72       200
weighted avg       0.73      0.71      0.71       200

Confusion matrix:
[[15  0  0  0  0  0  1  0  2  0]
 [ 0 19  1  0  0  2  0  0  0  1]
 [ 0  1 13  3  0  0  0  2  0  5]
 [ 0  1  1 11  1  0  0  2  2  7]
 [ 0  0  0  1 19  0  3  1  0  0]
 [ 0  2  1  0  0 11  0  0  1  0]
 [

In [ ]:
# Result of the cross validation for parameters selection Logistic Regression
print('Best parameters combination:')
print(' C: '+str(clf_LR.best_estimator_.C))
print(' Penalty: '+str(clf_LR.best_estimator_.penalty))
print(' Solver: '+str(clf_LR.best_estimator_.solver))
print(' Solver: '+str(clf_LR.best_estimator_.multi_class))

Best parameters combination:
 C: 614
 Penalty: l2
 Solver: saga
 Solver: multinomial


In [ ]:
# Random Forrest

# Random Search

space = dict()
space['n_estimators'] = (range(0,1000))
space['criterion']= ['gini', 'entropy']
space['min_samples_split'] = (range(2,10))
space['min_samples_leaf'] = (range(1,10))
space['max_features'] = ["auto", "sqrt", "log2"]
space['bootstrap'] = ['True', 'False']
space['oob_score'] = ['True', 'False']
space['warm_start'] = ['True', 'False']

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
model = RandomForestClassifier()

clf_RF = RandomizedSearchCV(model, space, scoring='accuracy', n_jobs=-1)
# Training
clf_RF = clf_RF.fit(X_train, y_train)

# Pred
y_pred_RF = clf_RF.predict(X_test)

# Classificaiton report
print('Classification report:')
print(classification_report(y_test, y_pred_RF))

# Confusion matrix
print('Confusion matrix:')
cm_RF = confusion_matrix(y_test, y_pred_RF)
print(cm_RF)

Classification report:
              precision    recall  f1-score   support

           0       0.71      0.67      0.69        18
           1       0.77      0.74      0.76        23
           2       0.68      0.54      0.60        24
           3       0.62      0.52      0.57        25
           4       0.84      0.67      0.74        24
           5       0.56      0.60      0.58        15
           6       0.67      0.95      0.78        21
           7       0.72      0.87      0.79        15
           8       0.60      0.53      0.56        17
           9       0.30      0.39      0.34        18

    accuracy                           0.65       200
   macro avg       0.65      0.65      0.64       200
weighted avg       0.66      0.65      0.64       200

Confusion matrix:
[[12  0  2  0  0  1  2  0  0  1]
 [ 0 17  1  0  0  5  0  0  0  0]
 [ 1  0 13  2  0  1  0  0  1  6]
 [ 0  1  1 13  2  0  1  2  0  5]
 [ 1  0  0  1 16  0  3  1  2  0]
 [ 0  4  1  0  0  9  0  0  1  0]
 [

In [ ]:
# Result of the cross validation for parameters selection Random Forrest
print('Best parameters combination:')
print(' n_estimators: '+str(clf_RF.best_estimator_.n_estimators))
print(' criterion: '+str(clf_RF.best_estimator_.criterion))
print(' min_samples_split: '+str(clf_RF.best_estimator_.min_samples_split))
print(' min_samples_leaf: '+str(clf_RF.best_estimator_.min_samples_leaf))
print(' max_features: '+str(clf_RF.best_estimator_.max_features))
print(' bootstrap: '+str(clf_RF.best_estimator_.bootstrap))
print(' oob_score: '+str(clf_RF.best_estimator_.oob_score))
print(' warm_start: '+str(clf_RF.best_estimator_.warm_start))

Best parameters combination:
 n_estimators: 519
 criterion: entropy
 min_samples_split: 5
 min_samples_leaf: 1
 max_features: auto
 bootstrap: True
 oob_score: False
 warm_start: False


In [ ]:
# Decision Tree

# Random Search

space = dict()
space['splitter'] = ['best', 'random']
space['criterion']= ['gini', 'entropy']
space['min_samples_split'] = (range(2,100))
space['min_samples_leaf'] = (range(1,100))
space['max_features'] = ["auto", "sqrt", "log2"]

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
model = DecisionTreeClassifier()

clf_DT = RandomizedSearchCV(model, space, scoring='accuracy', n_jobs=-1)
# Training
clf_DT = clf_DT.fit(X_train, y_train)

# Pred
y_pred_DT = clf_DT.predict(X_test)

# Classificaiton report
print('Classification report:')
print(classification_report(y_test, y_pred_DT))

# Confusion matrix
print('Confusion matrix:')
cm_DT = confusion_matrix(y_test, y_pred_DT)
print(cm_DT)


Classification report:
              precision    recall  f1-score   support

           0       0.44      0.22      0.30        18
           1       0.76      0.57      0.65        23
           2       0.33      0.21      0.26        24
           3       0.26      0.20      0.23        25
           4       0.54      0.62      0.58        24
           5       0.36      0.67      0.47        15
           6       0.58      0.90      0.70        21
           7       0.41      0.73      0.52        15
           8       0.50      0.41      0.45        17
           9       0.10      0.06      0.07        18

    accuracy                           0.45       200
   macro avg       0.43      0.46      0.42       200
weighted avg       0.43      0.45      0.42       200

Confusion matrix:
[[ 4  0  6  1  1  3  2  0  1  0]
 [ 0 13  0  0  0  7  0  1  0  2]
 [ 2  1  5  7  1  1  0  3  3  1]
 [ 0  0  2  5  6  2  3  4  0  3]
 [ 0  0  0  1 15  0  3  3  1  1]
 [ 1  3  0  1  0 10  0  0  0  0]
 [

In [ ]:
# Result of the cross validation for parameters selection Random Forrest
print('Best parameters combination:')
print(' splitter: '+str(clf_DT.best_estimator_.splitter))
print(' criterion: '+str(clf_DT.best_estimator_.criterion))
print(' min_samples_split: '+str(clf_DT.best_estimator_.min_samples_split))
print(' min_samples_leaf: '+str(clf_DT.best_estimator_.min_samples_leaf))
print(' max_features: '+str(clf_DT.best_estimator_.max_features))

Best parameters combination:
 splitter: best
 criterion: gini
 min_samples_split: 47
 min_samples_leaf: 20
 max_features: auto


In [ ]:
# KNeighbors Classifier

# Random Search

space = dict()
space['n_neighbors'] = range(5,50)
space['algorithm']= ['auto', 'ball_tree', 'kd_tree', 'brute']
space['p'] = [1, 2]

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
model = KNeighborsClassifier()

clf_KN = RandomizedSearchCV(model, space, scoring='accuracy', n_jobs=-1)
# Training
clf_KN = clf_KN.fit(X_train, y_train)

# Pred
y_pred_KN = clf_KN.predict(X_test)

# Classificaiton report
print('Classification report:')
print(classification_report(y_test, y_pred_KN))

# Confusion matrix
print('Confusion matrix:')
cm_KN = confusion_matrix(y_test, y_pred_KN)
print(cm_KN)

Classification report:
              precision    recall  f1-score   support

           0       0.72      0.72      0.72        18
           1       0.74      0.87      0.80        23
           2       0.59      0.83      0.69        24
           3       0.75      0.72      0.73        25
           4       0.76      0.67      0.71        24
           5       0.80      0.53      0.64        15
           6       0.80      0.95      0.87        21
           7       0.70      0.93      0.80        15
           8       0.44      0.24      0.31        17
           9       0.50      0.33      0.40        18

    accuracy                           0.69       200
   macro avg       0.68      0.68      0.67       200
weighted avg       0.69      0.69      0.68       200

Confusion matrix:
[[13  0  3  0  0  1  0  0  0  1]
 [ 0 20  2  0  0  1  0  0  0  0]
 [ 0  1 20  0  0  0  0  2  0  1]
 [ 0  1  2 18  0  0  1  1  0  2]
 [ 1  0  0  1 16  0  2  2  2  0]
 [ 0  5  1  0  0  8  0  0  1  0]
 [

In [ ]:
# Result of the cross validation for parameters selection Random Forrest
print('Best parameters combination:')
print(' n_neighbors: '+str(clf_KN.best_estimator_.n_neighbors))
print(' algorithm: '+str(clf_KN.best_estimator_.algorithm))
print(' mp: '+str(clf_KN.best_estimator_.p))

Best parameters combination:
 n_neighbors: 6
 algorithm: auto
 mp: 1


In [ ]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential()
model.add(Dense(1024, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(512, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
history = model.fit(X_train, y_train, epochs=100, batch_size=128)

Epoch 1/100
7/7 [==============================] - 2s 4ms/step - loss: 2.2499 - accuracy: 0.2074
Epoch 2/100
7/7 [==============================] - 0s 2ms/step - loss: 1.9132 - accuracy: 0.3492
Epoch 3/100
7/7 [==============================] - 0s 2ms/step - loss: 1.6220 - accuracy: 0.4311
Epoch 4/100
7/7 [==============================] - 0s 2ms/step - loss: 1.4068 - accuracy: 0.4705
Epoch 5/100
7/7 [==============================] - 0s 2ms/step - loss: 1.2756 - accuracy: 0.5239
Epoch 6/100
7/7 [==============================] - 0s 3ms/step - loss: 1.1908 - accuracy: 0.5580
Epoch 7/100
7/7 [==============================] - 0s 2ms/step - loss: 1.1685 - accuracy: 0.5531
Epoch 8/100
7/7 [==============================] - 0s 2ms/step - loss: 1.0829 - accuracy: 0.6115
Epoch 9/100
7/7 [==============================] - 0s 2ms/step - loss: 1.0106 - accuracy: 0.6318
Epoch 10/100
7/7 [==============================] - 0s 2ms/step - loss: 1.0166 - accuracy: 0.6211
Epoch 11/100
7/7 [===========

In [ ]:
test_loss, test_acc  = model.evaluate(X_test, y_test, batch_size=128)

2/2 [==============================] - 0s 4ms/step - loss: 1.4478 - accuracy: 0.7000
