In [ ]:
# Librerie Generiche

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from time import time
import seaborn as sn

# Keras
import keras
from keras.utils import to_categorical

# Sklearn
import sklearn
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV,  RepeatedStratifiedKFold
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, accuracy_score, roc_curve, classification_report
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.utils.estimator_checks import check_estimator

np.random.seed(1234)
tf.random.set_seed(1234)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
Music = pd.read_csv('/content/Music_3_seconds_datatset.csv')
Music = Music.drop(columns=['Unnamed: 0'])

In [ ]:
Music

filename  Mean_ZCR   Var_ZCR  ...  Var_MFCC_19  Var_MFCC_20  Genre
0     blues.00000.0.wav  0.081851  0.000558  ...    33.608330    43.827777  Blues
1     blues.00000.1.wav  0.087173  0.001030  ...    96.975451    60.006120  Blues
2     blues.00000.2.wav  0.071383  0.000425  ...    53.116809    33.136236  Blues
3     blues.00000.3.wav  0.069426  0.000304  ...    51.420635    31.930043  Blues
4     blues.00000.4.wav  0.070102  0.000288  ...    26.686307    29.212284  Blues
...                 ...       ...       ...  ...          ...          ...    ...
9975   rock.00099.5.wav  0.075849  0.002607  ...    40.042092    16.706747   Rock
9976   rock.00099.6.wav  0.058830  0.000383  ...    50.209189    39.865002   Rock
9977   rock.00099.7.wav  0.072885  0.000661  ...    48.812855    38.993574   Rock
9978   rock.00099.8.wav  0.089111  0.000987  ...    63.390674    18.759731   Rock
9979   rock.00099.9.wav  0.072194  0.003784  ...    48.307680    41.750015   Rock

[9980 rows x 59 columns]

In [ ]:
dati_X = Music.drop(columns=['Genre', 'filename'])
X = dati_X.values
min_max_scaler_x = sklearn.preprocessing.MinMaxScaler()
X_scale = min_max_scaler_x.fit_transform(X)
X_scale

array([[0.20445758, 0.00847825, 0.62778287, ..., 0.05530271, 0.02661089,
        0.04782937],
       [0.22038394, 0.01571868, 0.62731684, ..., 0.07519716, 0.08208627,
        0.06559999],
       [0.17313312, 0.00644692, 0.62809121, ..., 0.0712388 , 0.04368978,
        0.03608556],
       ...,
       [0.17762892, 0.01006393, 0.62884734, ..., 0.04410298, 0.03992184,
        0.04251938],
       [0.22618352, 0.01506607, 0.62902882, ..., 0.08108372, 0.05268414,
        0.02029411],
       [0.17556085, 0.05798272, 0.62999914, ..., 0.03597615, 0.03947958,
        0.04554711]])

In [ ]:
Y = Music['Genre']
LE = sklearn.preprocessing.LabelEncoder()
Y_label = LE.fit_transform(Y)

In [ ]:
X_scale.shape

(9980, 57)

In [ ]:
Y_label.shape

(9980,)

In [ ]:
X_train, X_test , y_train, y_test = train_test_split(X_scale, Y_label, test_size=0.2)

In [ ]:
X_train.shape

(7984, 57)

In [ ]:
X_test.shape

(1996, 57)

In [ ]:
y_train.shape

(7984,)

In [ ]:
y_test.shape

(1996,)

In [ ]:
y_train[0]

1

In [ ]:
# SVM

# Random Search

# Parameters to be tested in cross-validation
param_grid = {'C': [1e2, 5e2, 1e3],
          'gamma': [0.005, 0.01, 0.1, 0.5, 1.0], }

# Support Vector Machine initialization
clf_SVC = GridSearchCV(SVC(kernel='rbf', class_weight='balanced'), param_grid, cv=2)

# Training
t0 = time()
clf_SVC = clf_SVC.fit(X_train, y_train)
print('Training completed in %0.3fs' % (time() - t0))
# Test
y_pred_SVC = clf_SVC.predict(X_test)

In [ ]:
target_names = ['Blues', 'Classical', 'Country', 'Disco', 'Hiphop', 'Jazz', 'Metal', 'Pop', 'Reggae', 'Rock']
# Classificaiton report
print('Classification report:')
print(classification_report(y_test, y_pred_SVC, target_names= target_names))

# Confusion matrix
print('Confusion matrix:')
cm = confusion_matrix(y_test, y_pred_SVC)
print(cm)

Classification report:
              precision    recall  f1-score   support

       Blues       0.90      0.96      0.93       208
   Classical       0.96      0.99      0.98       218
     Country       0.88      0.85      0.87       192
       Disco       0.89      0.94      0.91       189
      Hiphop       0.89      0.92      0.90       193
        Jazz       0.93      0.96      0.94       205
       Metal       0.95      0.99      0.97       203
         Pop       0.94      0.87      0.90       200
      Reggae       0.93      0.90      0.92       187
        Rock       0.89      0.78      0.83       201

    accuracy                           0.92      1996
   macro avg       0.92      0.92      0.91      1996
weighted avg       0.92      0.92      0.92      1996

Confusion matrix:
[[199   0   2   2   2   0   0   0   2   1]
 [  0 216   0   0   0   2   0   0   0   0]
 [  4   3 164   0   1   6   0   2   3   9]
 [  1   2   2 177   0   0   1   1   2   3]
 [  0   0   1   4 177   0   

In [ ]:
# Result of the cross validation for parameters selection SVM
print('Best parameters combination SVM:')
print(' C: '+str(clf_SVC.best_estimator_.C))
print(' gamma: '+str(clf_SVC.best_estimator_.gamma))

Best parameters combination SVM:
 C: 100.0
 gamma: 1.0


In [ ]:
# LOGISTIC REGRESSION

# Random Search

space = dict()
space['solver'] = ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']
space['penalty'] = ['none', 'l1', 'l2', 'elasticnet']
space['C'] = (range(1,1000))
space['multi_class'] = ['auto', 'ovr', 'multinomial']
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
model = LogisticRegression()

clf_LR = RandomizedSearchCV(model, space, scoring='accuracy', n_jobs=-1)
# Training
clf_LR = clf_LR.fit(X_train, y_train)

# Pred
y_pred_LR = clf_LR.predict(X_test)

In [ ]:
# Classificaiton report
print('Classification report:')
print(classification_report(y_test, y_pred_LR, target_names=target_names))

# Confusion matrix
print('Confusion matrix:')
cm_LR = confusion_matrix(y_test, y_pred_LR)
print(cm_LR)

Classification report:
              precision    recall  f1-score   support

       Blues       0.67      0.63      0.65       208
   Classical       0.94      0.95      0.95       218
     Country       0.62      0.65      0.63       192
       Disco       0.63      0.69      0.66       189
      Hiphop       0.70      0.63      0.66       193
        Jazz       0.78      0.82      0.80       205
       Metal       0.77      0.89      0.82       203
         Pop       0.78      0.81      0.80       200
      Reggae       0.60      0.60      0.60       187
        Rock       0.56      0.41      0.47       201

    accuracy                           0.71      1996
   macro avg       0.70      0.71      0.70      1996
weighted avg       0.71      0.71      0.71      1996

Confusion matrix:
[[132   1  11   7   6   9  23   0   9  10]
 [  1 207   3   1   1   3   0   0   0   2]
 [ 15   1 124   9   2  11   2   3  11  14]
 [  1   2   5 131   7   0   1  12   8  22]
 [  5   0   5  10 122   1   

In [ ]:
# Result of the cross validation for parameters selection Logistic Regression
print('Best parameters combination Logistic Regression:')
print(' C: '+str(clf_LR.best_estimator_.C))
print(' Penalty: '+str(clf_LR.best_estimator_.penalty))
print(' Solver: '+str(clf_LR.best_estimator_.solver))
print(' Solver: '+str(clf_LR.best_estimator_.multi_class))

Best parameters combination Logistic Regression:
 C: 520
 Penalty: l2
 Solver: newton-cg
 Solver: ovr


In [ ]:
# Random Forrest

# Random Search

space = dict()
space['n_estimators'] = (range(0,1000))
space['criterion']= ['gini', 'entropy']
space['min_samples_split'] = (range(2,10))
space['min_samples_leaf'] = (range(1,10))
space['max_features'] = ["auto", "sqrt", "log2"]
space['bootstrap'] = ['True', 'False']
space['oob_score'] = ['True', 'False']
space['warm_start'] = ['True', 'False']

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
model = RandomForestClassifier()

clf_RF = RandomizedSearchCV(model, space, scoring='accuracy', n_jobs=-1)
# Training
clf_RF = clf_RF.fit(X_train, y_train)

# Pred
y_pred_RF = clf_RF.predict(X_test)

In [ ]:
# Classificaiton report
print('Classification report:')
print(classification_report(y_test, y_pred_RF, target_names=target_names))

# Confusion matrix
print('Confusion matrix:')
cm_RF = confusion_matrix(y_test, y_pred_RF)
print(cm_RF)

Classification report:
              precision    recall  f1-score   support

       Blues       0.90      0.84      0.87       208
   Classical       0.93      0.97      0.95       218
     Country       0.80      0.82      0.81       192
       Disco       0.87      0.88      0.87       189
      Hiphop       0.92      0.87      0.89       193
        Jazz       0.85      0.90      0.87       205
       Metal       0.90      0.96      0.93       203
         Pop       0.90      0.90      0.90       200
      Reggae       0.82      0.88      0.85       187
        Rock       0.92      0.77      0.83       201

    accuracy                           0.88      1996
   macro avg       0.88      0.88      0.88      1996
weighted avg       0.88      0.88      0.88      1996

Confusion matrix:
[[175   0   8   4   2   5   8   0   4   2]
 [  0 211   1   0   0   4   0   0   1   1]
 [  6   5 158   2   1   9   1   0   9   1]
 [  0   1   5 167   6   2   0   4   3   1]
 [  2   0   3   4 168   0   

In [ ]:
# Result of the cross validation for parameters selection Random Forrest
print('Best parameters combination Random Forrest:')
print(' n_estimators: '+str(clf_RF.best_estimator_.n_estimators))
print(' criterion: '+str(clf_RF.best_estimator_.criterion))
print(' min_samples_split: '+str(clf_RF.best_estimator_.min_samples_split))
print(' min_samples_leaf: '+str(clf_RF.best_estimator_.min_samples_leaf))
print(' max_features: '+str(clf_RF.best_estimator_.max_features))
print(' bootstrap: '+str(clf_RF.best_estimator_.bootstrap))
print(' oob_score: '+str(clf_RF.best_estimator_.oob_score))
print(' warm_start: '+str(clf_RF.best_estimator_.warm_start))

Best parameters combination Random Forrest:
 n_estimators: 428
 criterion: gini
 min_samples_split: 3
 min_samples_leaf: 1
 max_features: auto
 bootstrap: False
 oob_score: True
 warm_start: True


In [ ]:
# Decision Tree

# Random Search

space = dict()
space['splitter'] = ['best', 'random']
space['criterion']= ['gini', 'entropy']
space['min_samples_split'] = (range(2,100))
space['min_samples_leaf'] = (range(1,100))
space['max_features'] = ["auto", "sqrt", "log2"]

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
model = DecisionTreeClassifier()

clf_DT = RandomizedSearchCV(model, space, scoring='accuracy', n_jobs=-1)
# Training
clf_DT = clf_DT.fit(X_train, y_train)

# Pred
y_pred_DT = clf_DT.predict(X_test)

In [ ]:
# Classificaiton report
print('Classification report:')
print(classification_report(y_test, y_pred_DT, target_names=target_names))

# Confusion matrix
print('Confusion matrix:')
cm_DT = confusion_matrix(y_test, y_pred_DT)
print(cm_DT)

Classification report:
              precision    recall  f1-score   support

       Blues       0.38      0.38      0.38       208
   Classical       0.81      0.83      0.82       218
     Country       0.33      0.37      0.35       192
       Disco       0.55      0.44      0.49       189
      Hiphop       0.49      0.53      0.51       193
        Jazz       0.52      0.56      0.54       205
       Metal       0.67      0.68      0.68       203
         Pop       0.70      0.67      0.68       200
      Reggae       0.42      0.36      0.39       187
        Rock       0.40      0.41      0.41       201

    accuracy                           0.53      1996
   macro avg       0.53      0.52      0.52      1996
weighted avg       0.53      0.53      0.53      1996

Confusion matrix:
[[ 79   8  37   7  15  15  22   1  12  12]
 [  0 181   7   1   3  22   1   0   0   3]
 [ 33   5  71  17   0  24   7   1  13  21]
 [  6   4  19  83  26   7   3   8  16  17]
 [ 13   1   8   8 103   1   

In [ ]:
# Result of the cross validation for parameters selection Decision Tree
print(' splitter: '+str(clf_DT.best_estimator_.splitter))
print(' criterion: '+str(clf_DT.best_estimator_.criterion))
print(' min_samples_split: '+str(clf_DT.best_estimator_.min_samples_split))
print(' min_samples_leaf: '+str(clf_DT.best_estimator_.min_samples_leaf))
print(' max_features: '+str(clf_DT.best_estimator_.max_features))

Best parameters combination Random Forrest:
 splitter: best
 criterion: gini
 min_samples_split: 96
 min_samples_leaf: 2
 max_features: auto


In [ ]:
# KNeighbors Classifier

# Random Search

space = dict()
space['n_neighbors'] = range(5,50)
space['algorithm']= ['auto', 'ball_tree', 'kd_tree', 'brute']
space['p'] = [1, 2]

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
model = KNeighborsClassifier()

clf_KN = RandomizedSearchCV(model, space, scoring='accuracy', n_jobs=-1)
# Training
clf_KN = clf_KN.fit(X_train, y_train)

# Pred
y_pred_KN = clf_KN.predict(X_test)

In [ ]:
# Classificaiton report
print('Classification report:')
print(classification_report(y_test, y_pred_KN, target_names=target_names))

# Confusion matrix
print('Confusion matrix:')
cm_KN = confusion_matrix(y_test, y_pred_KN)
print(cm_KN)

Classification report:
              precision    recall  f1-score   support

       Blues       0.90      0.87      0.88       208
   Classical       0.89      0.97      0.93       218
     Country       0.81      0.86      0.83       192
       Disco       0.81      0.92      0.86       189
      Hiphop       0.89      0.90      0.89       193
        Jazz       0.89      0.86      0.88       205
       Metal       0.96      0.94      0.95       203
         Pop       0.93      0.85      0.89       200
      Reggae       0.87      0.89      0.88       187
        Rock       0.90      0.80      0.85       201

    accuracy                           0.89      1996
   macro avg       0.89      0.89      0.89      1996
weighted avg       0.89      0.89      0.89      1996

Confusion matrix:
[[180   1  11   4   0   1   0   0   8   3]
 [  0 211   0   0   0   6   0   0   0   1]
 [  5   6 165   5   1   5   0   0   4   1]
 [  0   2   1 173   5   1   1   1   3   2]
 [  1   0   3   4 174   1   

In [ ]:
# Result of the cross validation for parameters selection KNeighbors Classifier
print('Best parameters combination KNeighbors Classifier:')
print(' n_neighbors: '+str(clf_KN.best_estimator_.n_neighbors))
print(' algorithm: '+str(clf_KN.best_estimator_.algorithm))
print(' mp: '+str(clf_KN.best_estimator_.p))

Best parameters combination KNeighbors Classifier:
 n_neighbors: 7
 algorithm: auto
 mp: 2


In [ ]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential()
model.add(Dense(1024, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(512, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
history = model.fit(X_train, y_train, epochs=100, batch_size=128)

Epoch 1/100
63/63 [==============================] - 2s 2ms/step - loss: 1.9334 - accuracy: 0.3050
Epoch 2/100
63/63 [==============================] - 0s 2ms/step - loss: 1.2557 - accuracy: 0.5288
Epoch 3/100
63/63 [==============================] - 0s 2ms/step - loss: 1.0993 - accuracy: 0.5975
Epoch 4/100
63/63 [==============================] - 0s 2ms/step - loss: 0.9858 - accuracy: 0.6408
Epoch 5/100
63/63 [==============================] - 0s 2ms/step - loss: 0.8979 - accuracy: 0.6812
Epoch 6/100
63/63 [==============================] - 0s 2ms/step - loss: 0.9258 - accuracy: 0.6663
Epoch 7/100
63/63 [==============================] - 0s 2ms/step - loss: 0.8277 - accuracy: 0.7047
Epoch 8/100
63/63 [==============================] - 0s 2ms/step - loss: 0.8083 - accuracy: 0.7151
Epoch 9/100
63/63 [==============================] - 0s 2ms/step - loss: 0.7849 - accuracy: 0.7194
Epoch 10/100
63/63 [==============================] - 0s 2ms/step - loss: 0.7650 - accuracy: 0.7294
Epoch 11/

In [ ]:
test_loss, test_acc  = model.evaluate(X_test, y_test, batch_size=128)

16/16 [==============================] - 0s 2ms/step - loss: 0.5205 - accuracy: 0.8788
